Repository wecode-bootcamp-korea/40-1st-Dyong-frontend, pull requests merged in 2022-12, with the labels that each got.

#1 [40기 김민서] 회원가입/로그인(완)
  src/Router.js
  src/components/Input/HintInput.js
  src/components/Input/Input.js
  src/index.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 완료

#6 [40기 임지인]LIST 레이아웃 구축
  public/images/lovey_teat_box.jpg
  public/images/malcha.jpg
  public/images/malcha_banner.jpg
  public/images/osulloc_banner.jpg
  public/images/premium_tea.jpg
  public/images/premium_tea_banner.jpg
  public/images/tea_set_banner.jpg
  public/images/우전.jpg
  src/Router.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/jeein/Malcha.js
  src/pages/Product/jeein/PremiumTea.js
  src/pages/Product/jeein/Product.js
  src/pages/Product/jeein/Product.scss
  src/pages/Product/jeein/TeaSet.js
Labels: Conflict 해결 요청, 완료

#5 [40기 문다연] - Add: footer 레이아웃 구현
  public/images/LogoIcon.png
  public/images/images.png
  public/index.html
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: 완료

#4 [40기 문다연] GNB 구현
  public/images/Logo.png
  public/images/LogoIcon.png
  src/components/Drawer/Drawer.js
  src/components/Drawer/Drawer.scss
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/styles/common.scss
Labels: 완료

#3 [40기 임지인] List Query String 구현
  public/data/sample.json
  public/images/osulloc_main(1).jpg
  public/images/osulloc_main(2).jpg
  public/images/osulloc_main(3).jpg
  public/images/osulloc_main(4).jpg
  src/Router.js
  src/components/Footer/Footer.scss
  src/pages/Detail/Detail.scss
  src/pages/Detail/ProductsDetail.js
  src/pages/Main/Main.js
  src/pages/Product/Detail/Detail.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/jeein/Malcha.js
  src/pages/Product/jeein/PremiumTea.js
  src/pages/Product/jeein/Product.js
  src/pages/Product/jeein/TeaSet.js
  src/styles/common.scss
Labels: 완료

#8 [40기 문다연] 장바구니 구현
  src/Router.js
  src/components/Drawer/Drawer.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/styles/common.scss
Labels: 완료

#11 [40기 문다연] GNB 구현
  src/components/Drawer/Drawer.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#7 [40기 김민서] 제품 상세 페이지
  public/images/one.png
  public/images/three.png
  public/images/two.png
  src/Router.js
  src/components/Input/HintInput.js
  src/components/Input/HintInput.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Product/Detail/Detail.js
  src/pages/Product/Detail/Detail.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#12 [40기 문다연] 장바구니 구현
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
Labels: 멘토 리뷰 요청

#10 [40기 임지인] List Pagination 구현
  public/data/sample.json
  src/Router.js
  src/pages/Detail/ProductsDetail.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
Labels: 멘토 리뷰 요청

#13 [40기 문다연] FIX: router config & fetch api url
  src/Router.js
  src/components/Drawer/Drawer.scss
  src/components/Nav/Nav.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Login/Login.js
  src/pages/Product/Detail/Detail.js
  src/pages/Signup/Signup.js
Labels: 완료

#14 login.js랑 detail.js에 수정부분입니다. (토큰생성관련)
  src/pages/Product/Detail/Detail.js
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청
